### ISSUE TITLE
【bug】编辑器左边那一列空了一个字符

### ISSUE THREAD

**Issue by fslongjin** [DragonOS-Community/Held#3]
如图所示，刚打开编辑器的时候，左边那列会发现空了一个字符。

![image](https://github.com/DragonOS-Community/Held/assets/63215266/7d596edb-249a-41a0-8d7b-f4c0b490c385)

**Comment by GnoCiYeH** [comment]
这个是正常的，标志你目前文件到哪行结束

**Comment by fslongjin** [comment]
感觉像vim那样把`~`放到正文的末尾会好一些？

**Comment by GnoCiYeH** [comment]
哈哈哈哈这个我应该改成背景颜色一致，但是有内容才输出``~``，这样就不会有这种视觉上的不舒适
